#!/bin/bash

#PBS -l walltime=12:00:00,select=1:ncpus=32:mem=128gb
#PBS -N rCPM_1ABC_p05
#PBS -m abe
#PBS -M srfrew@uwaterloo.ca
#PBS -A st-tv01-1
#PBS -e rCPM_1ABC_p01_errout1-p05-OCD.txt
#PBS -o rCPM_1ABC_p01_stdout1-p05-OCD.txt

#################### PBS  script ###################
 
cd $PBS_O_WORKDIR

module load matlab 
matlab -nodisplay -r "run /scratch/st-tv01-1/ocd/analysis/part1/rCPM_1ABC_p05.m; quit;"