#!/bin/bash

#PBS -l walltime=12:00:00,select=1:ncpus=32:mem=128gb
#PBS -N cohort1A_rcpm_iter
#PBS -m abe
#PBS -M srfrew@uwaterloo.ca
#PBS -A st-tv01-1
#PBS -e cohort1A_rcpm_iter_errout.txt
#PBS -o cohort1A_rcpm_iter_stdout.txt

#################### PBS  script ###################

cd $PBS_O_WORKDIR

module load matlab 
matlab -nodisplay -r "run /scratch/st-tv01-1/ocd/analysis/part1/cohort1A_rcpm_iter.m; quit;"
